name: echo-everytime
on:
 push:

jobs:
  echos:
    runs-on: windows-latest
    steps:
      - name: echos
        shell: bash
        run: |
          echo "Start Actions"
          echo $RELEASE_VERSION
          echo repo1=${{ github.repository }}
          echo repo2=${{ github.event.repository.name }}
          echo ref_=${{ github.ref }}
          echo href=${{ github.head_ref }}
          echo sha_=${{ github.sha }}
          echo workspace=${{ github.workspace }}
          echo tag_=${GITHUB_REF#refs/*/}
          echo REF1=$GITHUB_REF
          echo REF3=${GITHUB_REF##*/}
          echo REF4=${GITHUB_REF/refs\/tags\/v/}
          echo "repo=${{ github.event.repository.name }}" >> $GITHUB_ENV
          echo "version=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
          echo REPOSITORY=${{ env.repo }}"
          echo VERSION=${{ env.version }}"

      - name: echos2
        shell: bash
        run: |
          echo $RELEASE_VERSION
          echo "REPOSITORY=${{ env.repo }}"
          echo "VERSION=${{ env.version }}"

