name: learn-github-actions
on: [push]
jobs:
  check-bats-version:    
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello, world!
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install -g bats
      - run: bats -v
