name: learn-github-actions
on: [push]
jobs:
  echos:
    runs-on: windows-latest
    steps:
      - name: echo output
        shell: bash
        run: |
          echo Print_Repository_and_Version
          echo $RELEASE_VERSION
          echo repo_full=${{ github.repository }}
          echo GITHUB_REF=$GITHUB_REF
          echo "repo=${{ github.event.repository.name }}" >> $GITHUB_ENV
          echo "version=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
          echo REPOSITORY=${{ env.repo }}"
          echo VERSION=${{ env.version }}"

      - name: echos
        shell: bash
        run: |
          echo $RELEASE_VERSION
          echo repo1=${{ github.repository }}
          echo repo2=${{ github.event.repository.name }}
          echo ref_=${{ github.ref }}
          echo href=${{ github.head_ref }}
          echo sha_=${{ github.sha }}
          echo workspace=${{ github.workspace }}
          echo tag_=${GITHUB_REF#refs/*/}
          echo REF1=$GITHUB_REF
          echo REF3=${GITHUB_REF##*/}
          echo REF4=${GITHUB_REF/refs\/tags\/v/}
          echo "repo=${{ github.event.repository.name }}" >> $GITHUB_ENV
          echo "version=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
          echo REPOSITORY=${{ env.repo }}"
          echo VERSION=${{ env.version }}"

      - name: echos2
        shell: bash
        run: |
          echo $RELEASE_VERSION
          echo "REPOSITORY=${{ env.repo }}"
          echo "VERSION=${{ env.version }}"

      - name: Save output
        shell: bash
        run: |
          expr 1 + 1 > output_${{ env.version }}.log

      - uses: actions/upload-artifact@v1
        with:
          name: output_${{ env.version }}-log-file
          path: output_${{ env.version }}.log

      - uses: actions/download-artifact@v2
        with:
          name: output_${{ env.version }}-log-file

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: ${{ env.version }}
          release_name: Version ${{ env.version }}
          body: |
            - hogehoge
            - homuhomu
          draft: true
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: output_${{ env.version }}.log
          asset_name: output_${{ env.version }}-log-file
          asset_content_type: application/zip
