name: learn-github-actions
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - run: ./setup_server.sh

  build_job:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: ./build_server.sh
        
  test_job:
    needs: build_job
    runs-on: ubuntu-latest
    steps:
      - run: ./test_server.sh

