name: learn-github-actions
on: [push]
jobs:   
  job_1:
    name: calc 3 + 7
    runs-on: ubuntu-latest
    steps:
      - name: calc
        shell: bash
        run: |
          expr 3 + 7 > math-homework.txt
      - uses: actions/upload-artifact@v2
        with:
          name: homework
          path: math-homework.txt

  job_2:
    name: calc x 9
    needs: job_1
    runs-on: windows-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: homework
      - name: calc
        shell: bash
        run: |
          value=`cat math-homework.txt`
          expr $value \* 9 > math-homework.txt
      - uses: actions/upload-artifact@v2
        with:
          name: homework
          path: math-homework.txt

  job_3:
    name: display results
    needs: job_2
    runs-on: macos-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: homework
      - name: print results
        shell: bash
        run: |
          value=`cat math-homework.txt`
          echo the result is $value