name: learn-github-actions
on:
 push:
  tags:
    - v*

jobs:
  echos:
    runs-on: windows-latest
    needs: echos_everytime
    steps:
      - name: Save output
        shell: bash
        run: |
          expr 1 + 1 > output_${{ env.version }}.log

      - uses: actions/upload-artifact@v1
        with:
          name: output_${{ env.version }}-log-file
          path: output_${{ env.version }}.log

      - uses: actions/download-artifact@v2
        with:
          name: output_${{ env.version }}-log-file

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: ${{ env.version }}
          release_name: Version ${{ env.version }}
          body: |
            - hogehoge
            - homuhomu
          draft: true
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: output_${{ env.version }}.log
          asset_name: output_${{ env.version }}-log-file
          asset_content_type: application/zip
