name: learn-github-actions
on: [push]
jobs:
  echos:
    runs-on: windows-latest
    steps:
      - name: echos
        shell: bash
        run: |
          echo $RELEASE_VERSION
          echo repo=${{ github.repository }}
          echo ref_=${{ github.ref }}
          echo href=${{ github.head_ref }}
          echo sha_=${{ github.sha }}
          echo workspace=${{ github.workspace }}
          echo tag_=${GITHUB_REF#refs/*/}
          echo REF1=$GITHUB_REF
          echo REF3=${GITHUB_REF##*/}
          echo REF4=${GITHUB_REF/refs\/tags\/v/}
          echo ${{ github.repository }} | sed -e "s#.*/##" >> $REPO
          echo ${{ github.ref }} | sed -e "s#refs/tags/##g" >> $VER
          echo REPOSITORY=$REPO
          echo VERSION=$VER

      - name: echos2
        shell: bash
        run: |
          echo $RELEASE_VERSION
          echo REPOSITORY=$REPO
          echo VERSION=$VER

      - name: Save output
        shell: bash
        run: |
          expr 1 + 1 > output_$VER.log
      
      - uses: actions/upload-artifact@v1
        with:
          name: output_$VER-log-file
          path: output_$VER.log
      
      - uses: actions/download-artifact@v2
        with:
          name: output_$VER-log-file

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: $VERSION
          release_name: Version $VERSION
          body: |
            - hogehoge
            - homuhomu
          draft: true
          prerelease: false


